### PR TITLE
fix: add oidc params to vex walker

### LINKED ISSUE #547: Use public API for vexination-walker
At the moment the vexination-walker has direct access to s3 infrastructure, but we need to make it run using the public API. This allows us to run the walker processes externally and at a more appropriate time since we don't have access to s3 credentials outside the cluster.

### PR DESCRIPTION
**Pull request by jcrossley3**
Fixes #547 again

### CODE REVIEW

File: vexination/walker/src/server.rs [hunk 1]
```diff
@@ -7,32 +7,48 @@ use csaf_walker::{
...
         let sink = sink.clone();
+        let provider = provider.clone();
         async move {
             match advisory {
                 Ok(ValidatedAdvisory { retrieved }) => {
                     let data = retrieved.data;
                     match serde_json::from_slice::<csaf::Csaf>(&data) {
-                        Ok(doc) => match reqwest::Client::new().post(sink).json(&doc).send().await {
-                            Ok(_) => {
+                        Ok(doc) => match reqwest::Client::new()
```
Comment (ctron) [inline vexination/walker/src/server.rs:33]: I now it has nothing to do with this PR, but I think there should be a single client which gets reused. 

Citing the docs:

> **NOTE:** If you plan to perform multiple requests, it is best to create a [Client](https://docs.rs/reqwest/0.11.20/reqwest/struct.Client.html) and reuse it, taking advantage of keep-alive connection pooling.

https://docs.rs/reqwest/0.11.20/reqwest/#making-a-get-request

**Review by ctron — APPROVED** [review]
