### PR TITLE
fix: ensure keys are sent to indexed topic after snapshot is published

### LINKED ISSUE #393: The `sbom-indexed` event may be premature
At present, there is an unpredictable delay between when an `sbom-indexed` event is received and when the SBOM attributes are actually available in the index.

### PR DESCRIPTION
**Pull request by lulf**
Fixes #393

### CODE REVIEW

**Review by jcrossley3 — APPROVED** [review]
Nice. This seems to replace the old `events` counter with a Vector of keys.

File: indexer/src/lib.rs [hunk 1]
```diff
@@ -130,7 +132,7 @@ impl<'a, INDEX: Index> Indexer<'a, INDEX> {
                                             EventType::Put => {
                                                 match self.storage.get_for_event(&data).await {
                                                     Ok((k, data)) => {
-                                                        if let Err(e) = self.index_doc(self.index.index(), writer.as_mut().unwrap(), &k, &data).await {
+                                                        if let Err(e) = self.index_doc(self.index.index(), writer.as_mut().unwrap(), &k, &data, &mut indexed).await {
                                                             log::warn!("(Ignored) Internal error when indexing {}: {:?}", k, e);
                                                         }
                                                         events += 1;
```
Comment (jcrossley3) [inline indexer/src/lib.rs:138]: Actually, after submitting my review, *then* I noticed the `events` counter is still around... why not just check if `indexed` is empty instead?

Comment (lulf) [reply indexer/src/lib.rs:138]: It wouldn't catch the 'deleted' events so using indexed is empty() would cause it to miss publishing snapshots of deleted documents.

Comment (jcrossley3) [reply indexer/src/lib.rs:138]: Speaking of that, I found myself wanting an event when an SBOM was deleted from the index as well as added -- i.e. I want to know the index has changed in any form or fashion. So `indexed` might hold structs with fields for `key` and `action` maybe -- denoting whether the key was added or removed -- and those same structs could be sent to the `indexed` topic.

Just a thought.

Comment (lulf) [reply indexer/src/lib.rs:138]: Yeah, maybe renaming/repurposing it to sbom-changed along with key and event type.
